version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/client/"
    schedule:
      interval: "weekly"
    reviewers:
      - "marchellodev"
      - "DmytroKolisnyk2"
      - "yeontannie"

  - package-ecosystem: "nuget"
    directory: "/server/Publications/"
    schedule:
      interval: "weekly"
    reviewers:
      - "marchellodev"
      - "PrudiusVladislav"
      - "Pivdenna"
    allow:
      - dependency-type: "all"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
    ignore:
      - dependency-name: "*"
        versions: ["-beta", "-alpha", "-rc", "-preview"]
