version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/client/"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"
    reviewers:
      - "marchellodev"
      - "DmytroKolisnyk2"
      - "yeontannie"
