
services:
  publications.api:
    image: publications.api:production
    container_name: publications.api.production
    build:
      context: .
      dockerfile: Publications.API/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Notion__AuthToken=${NOTION_AUTH_TOKEN}
      - DbSync__Key=${DB_SYNC_KEY}
    volumes:
      - sqlite-data-production:/app/sqlite_db
    networks:
      - backend-network
      - prod-network

  redis:
    image: redis/redis-stack
    container_name: redis.production
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis-data-production:/data
    networks:
      - backend-network

volumes:
  redis-data-production:
  sqlite-data-production:

networks:
  prod-network:
    external: true
    name: prod-network
  backend-network:
    driver: bridge
