
services:
  publications.api:
    image: publications.api:production
    container_name: publications.api.production
    build:
      context: .
      dockerfile: Publications.API/Dockerfile
    restart: on-failure
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Notion__AuthToken=${NOTION_AUTH_TOKEN}
    volumes:
      - sqlite-data-production:/app/sqlite_db

  redis:
    image: redis/redis-stack
    container_name: redis.production
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis-data-production:/data

volumes:
  redis-data-production:
  sqlite-data-production:
