
services:
  publications.api:
    image: publications.api:staging
    container_name: publications.api.staging
    build:
      context: .
      dockerfile: Publications.API/Dockerfile
    restart: on-failure
    ports:
      - "3000:8080"
      - "3001:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - Notion__AuthToken=${NOTION_AUTH_TOKEN}
      - DbSync__Key=${DB_SYNC_KEY}
      - Redis__Password=${REDIS_PASSWORD}
    volumes:
      - sqlite-data-staging:/app/sqlite_db

  redis:
    image: redis/redis-stack
    container_name: redis.staging
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - redis-data-staging:/data

volumes:
  redis-data-staging:
  sqlite-data-staging:
