
services:
  publications.api:
    image: publications.api:production
    container_name: publications.api.production
    build:
      context: .
      dockerfile: Publications.API/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Notion__AuthToken=${NOTION_AUTH_TOKEN}
      - DbSync__Key=${DB_SYNC_KEY}
      - Redis__Password=${REDIS_PASSWORD}
    volumes:
      - sqlite-data-production:/app/sqlite_db
    networks:
      - prod-network

  redis:
    image: redis/redis-stack
    container_name: redis.production
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8001:8001"
    volumes:
      - redis-data-production:/data
    networks:
      - prod-network

volumes:
  redis-data-production:
  sqlite-data-production:

networks:
  prod-network:
    external: true
    name: prod-network
