
services:
  publications.api:
    image: publications.api:staging
    container_name: publications.api.staging
    build:
      context: .
      dockerfile: Publications.API/Dockerfile
    restart: on-failure
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    volumes:
      - sqlite-data-staging:/app/sqlite_db

  redis:
    image: redis/redis-stack
    container_name: redis.staging
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis-data-staging:/data

volumes:
  redis-data-staging:
  sqlite-data-staging:
