name: Deploy to VPS

on:
  push:
    branches: [ "main", "published" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Prepare known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS Staging
      if: github.ref == 'refs/heads/main'
      run: |
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP}} "~/staging/deploy.staging.sh"

    - name: Deploy to VPS Production
      if: github.ref == 'refs/heads/published'
      run: |
        sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP}} "~/production/deploy.production.sh"