name: Deploy to aws ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prepare ssh key and known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ec2-13-49-35-6.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
      
    - name: Deploy to EC2
      run: ssh -i ~/.ssh/deploy_key ec2-user@ec2-13-49-35-6.eu-north-1.compute.amazonaws.com "~/deploy.sh"